export default {
  "login": "mpj",
  "id": 17815,
  "node_id": "MDQ6VXNlcjE3ODE1",
  "avatar_url": "https://avatars.githubusercontent.com/u/17815?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/mpj",
  "html_url": "https://github.com/mpj",
  "followers_url": "https://api.github.com/users/mpj/followers",
  "following_url": "https://api.github.com/users/mpj/following{/other_user}",
  "gists_url": "https://api.github.com/users/mpj/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/mpj/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/mpj/subscriptions",
  "organizations_url": "https://api.github.com/users/mpj/orgs",
  "repos_url": "https://api.github.com/users/mpj/repos",
  "events_url": "https://api.github.com/users/mpj/events{/privacy}",
  "received_events_url": "https://api.github.com/users/mpj/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Mattias Petter Johansson",
  "company": "Mattias Petter Johansson",
  "blog": "http://mpj.me",
  "location": "Stockholm, Sweden",
  "email": null,
  "hireable": true,
  "bio": null,
  "twitter_username": null,
  "public_repos": 140,
  "public_gists": 131,
  "followers": 5627,
  "following": 19,
  "created_at": "2008-07-22T10:20:27Z",
  "updated_at": "2021-07-07T07:32:39Z"
}
